### ISSUE TITLE
Add Dedicated Sensors Instead of Attributes for More Granular Tracking

### ISSUE THREAD

**Issue by rafael-zilberman** [rafael-zilberman/device-maintenance-monitor-custom-component#9]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/rafael-zilberman/device-maintenance-monitor-custom-component/labels/enhancement).

### Is your feature request related to a problem? Please describe.

Using attributes for tracking various metrics can be limiting and less flexible.

### Describe the solution you'd like

Create dedicated sensors for each metric (e.g., runtime, power on count, fixed interval) to allow for more granular and flexible tracking.

### Additional context

Dedicated sensors would enhance the integration's compatibility with other Home Assistant features and improve overall usability.
